
spring:
   datasource:
      url: jdbc:mysql://192.168.56.103:6603/test_db
      username: testu
      password: testp
   jpa:
      show-sql: false
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            show_sql: false

batch:
   lineListeners: >
      uk.gav.batch.ConfirmationListener,
      uk.gav.batch.DiscountListener,
      uk.gav.batch.InvoiceListener
   letterSources: >
      uk.gav.letter.ConfirmationSource,
      uk.gav.letter.DiscountSource,
      uk.gav.letter.InvoiceSource
   dateProvider:
      uk.gav.date.TestDateProvider
   confirmation: uk.gav.output.FileTarget
   discount: uk.gav.output.FileTarget
   invoice: uk.gav.output.S3Target

output:
   fileTarget:
      directory: /home/regen/temp/output
   s3Target:
      uri: http://192.168.56.103:8001
      bucket: letters
      region: eu-west-2
      auth:
   AMQPTarget:
      host: 192.168.56.103
      port: 5672
      user: guest
      password: guest
      virtualHost: /
company:
   host: localhost
   port: 8081
     
---

spring:
   profiles: st
datasource:
   url: jdbc:h2:file:~/temp/data/q
   driverClassName: org.h2.Driver
   username: qman
   password: qman
h2:
   console:
      enabled: true
jpa:
   database-platform: org.hibernate.dialect.H2Dialect
   hibernate:
      ddl-auto: update
   properties:
      hibernate:
         show_sql: true
         use_sql_comments: false
         format_sql: false